/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rental.system.View;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import rental.system.Model.Property;
import rental.system.Control.Control;
import rental.system.Model.User;

/**
 *
 * @author alahm
 */
public class AgentOwnerPage extends javax.swing.JFrame {

    private static String newImagePath = "";
    private static String editImagePath = "";

    private static Vector<Property> holdTheDataOfProperties;

    private static User user;
    private static Property property;

    Control control = new Control();

    /**
     * Creates new form AgentOwnerPage
     */
    public AgentOwnerPage(User u) {
        initComponents();
        setIcon();
        user = u;
        displayPropertiesInfo();
        userNamejLabel.setText(user.getFullName());
        userIdjLabel.setText(String.valueOf(user.getId()));
        userTypejLabel.setText(user.getUserType());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barjPanel = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        userNamejLabel = new javax.swing.JLabel();
        userIdjLabel = new javax.swing.JLabel();
        userTypejLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        newPropertyBtn = new javax.swing.JButton();
        editPropertyrBtn = new javax.swing.JButton();
        containrjPanel = new javax.swing.JTabbedPane();
        newPropertyjPanel = new javax.swing.JPanel();
        newNamePropertjLabel = new javax.swing.JLabel();
        newPricejLabel = new javax.swing.JLabel();
        newPropertyjLabel = new javax.swing.JLabel();
        newNameProertField = new javax.swing.JTextField();
        newPricePropertyField = new javax.swing.JTextField();
        newTypePropertyjComboBox = new javax.swing.JComboBox<>();
        newFrunjLabel = new javax.swing.JLabel();
        newFurnjComboBox = new javax.swing.JComboBox<>();
        newFacjLabel = new javax.swing.JLabel();
        newMutltiCheckBox = new javax.swing.JCheckBox();
        newGymCheckBox = new javax.swing.JCheckBox();
        newSkyCheckBox = new javax.swing.JCheckBox();
        newCarCheckBox = new javax.swing.JCheckBox();
        newPlayCheckBox = new javax.swing.JCheckBox();
        newSwimmCheckBox = new javax.swing.JCheckBox();
        newReadingCheckBox = new javax.swing.JCheckBox();
        newImagePropertyjLabel = new javax.swing.JLabel();
        addNewProertyImage = new javax.swing.JLabel();
        clearPropertyFiledBtn = new javax.swing.JButton();
        newPrpertyselectBtn = new javax.swing.JButton();
        newPropertSubmitBtn = new javax.swing.JButton();
        newActivationLabel = new javax.swing.JLabel();
        newActivationjComboBox = new javax.swing.JComboBox<>();
        newBookjLabel = new javax.swing.JLabel();
        newBookjComboBox = new javax.swing.JComboBox<>();
        editPropertyjPanel = new javax.swing.JPanel();
        editNamejLabel = new javax.swing.JLabel();
        editPricejLabel = new javax.swing.JLabel();
        editTypejLabel = new javax.swing.JLabel();
        editNameField = new javax.swing.JTextField();
        editPriceField = new javax.swing.JTextField();
        editTypejComboBox = new javax.swing.JComboBox<>();
        editFurniturejLabel = new javax.swing.JLabel();
        editFurniturejComboBox = new javax.swing.JComboBox<>();
        editFacitltisejLabel = new javax.swing.JLabel();
        editMultijCheckBox = new javax.swing.JCheckBox();
        editPlayjCheckBox = new javax.swing.JCheckBox();
        editSkyjCheckBox = new javax.swing.JCheckBox();
        editGymjCheckBox = new javax.swing.JCheckBox();
        editCarParkjCheckBox = new javax.swing.JCheckBox();
        editPooljCheckBox = new javax.swing.JCheckBox();
        editReadingjCheckBox = new javax.swing.JCheckBox();
        editBookjLabel = new javax.swing.JLabel();
        editImagejLabel = new javax.swing.JLabel();
        newImage = new javax.swing.JLabel();
        editActivationjLabel = new javax.swing.JLabel();
        editDeletetBtn = new javax.swing.JButton();
        imageOld = new javax.swing.JLabel();
        newPicturejLabel = new javax.swing.JLabel();
        oldPicturejLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editTableViewProperties = new javax.swing.JTable();
        editSubmitBtn = new javax.swing.JButton();
        editActivationjComboBox = new javax.swing.JComboBox<>();
        editBookjComboBox = new javax.swing.JComboBox<>();
        editselectPictureBtn = new javax.swing.JButton();
        loadDataBtn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        addNewPropertMenu = new javax.swing.JMenuItem();
        jSeparatorMenu = new javax.swing.JPopupMenu.Separator();
        exitjMenu = new javax.swing.JMenuItem();
        editjMenu = new javax.swing.JMenu();
        editPropertyjMenuItem = new javax.swing.JMenuItem();
        viewjMenu = new javax.swing.JMenu();
        viewPropertyjMenuItem = new javax.swing.JMenuItem();
        helpjMenu = new javax.swing.JMenu();
        helpjMenuItem = new javax.swing.JMenuItem();
        aboutUsjMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cyberjaya online rental managment system - Agent /Owner");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barjPanel.setBackground(new java.awt.Color(0, 0, 26));
        barjPanel.setMaximumSize(new java.awt.Dimension(180, 540));
        barjPanel.setMinimumSize(new java.awt.Dimension(180, 540));
        barjPanel.setPreferredSize(new java.awt.Dimension(180, 540));

        userIcon.setForeground(new java.awt.Color(255, 255, 255));
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_user_100px.png"))); // NOI18N

        userNamejLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNamejLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userNamejLabel.setMaximumSize(new java.awt.Dimension(160, 22));
        userNamejLabel.setMinimumSize(new java.awt.Dimension(160, 22));
        userNamejLabel.setPreferredSize(new java.awt.Dimension(160, 22));

        userIdjLabel.setForeground(new java.awt.Color(255, 255, 255));
        userIdjLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userIdjLabel.setMaximumSize(new java.awt.Dimension(160, 22));
        userIdjLabel.setMinimumSize(new java.awt.Dimension(160, 22));
        userIdjLabel.setPreferredSize(new java.awt.Dimension(160, 22));

        userTypejLabel.setForeground(new java.awt.Color(255, 255, 255));
        userTypejLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userTypejLabel.setMaximumSize(new java.awt.Dimension(160, 22));
        userTypejLabel.setMinimumSize(new java.awt.Dimension(160, 22));
        userTypejLabel.setPreferredSize(new java.awt.Dimension(160, 22));

        newPropertyBtn.setBackground(new java.awt.Color(204, 204, 204));
        newPropertyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_new_copy_26px.png"))); // NOI18N
        newPropertyBtn.setText("New Property");
        newPropertyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPropertyBtnActionPerformed(evt);
            }
        });

        editPropertyrBtn.setBackground(new java.awt.Color(204, 204, 204));
        editPropertyrBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_edit_property_26px.png"))); // NOI18N
        editPropertyrBtn.setText("Edit Property");
        editPropertyrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPropertyrBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barjPanelLayout = new javax.swing.GroupLayout(barjPanel);
        barjPanel.setLayout(barjPanelLayout);
        barjPanelLayout.setHorizontalGroup(
            barjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barjPanelLayout.createSequentialGroup()
                .addGroup(barjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(barjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userIdjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userTypejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(barjPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(userIcon)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(barjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(newPropertyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(editPropertyrBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barjPanelLayout.setVerticalGroup(
            barjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIcon)
                .addGap(18, 18, 18)
                .addComponent(userNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userIdjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userTypejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(newPropertyBtn)
                .addGap(71, 71, 71)
                .addComponent(editPropertyrBtn)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        getContentPane().add(barjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        newPropertyjPanel.setBackground(new java.awt.Color(115, 181, 239));
        newPropertyjPanel.setLayout(null);

        newNamePropertjLabel.setText("Name");
        newPropertyjPanel.add(newNamePropertjLabel);
        newNamePropertjLabel.setBounds(20, 70, 40, 14);

        newPricejLabel.setText("Price");
        newPropertyjPanel.add(newPricejLabel);
        newPricejLabel.setBounds(20, 110, 40, 14);

        newPropertyjLabel.setText("Type");
        newPropertyjPanel.add(newPropertyjLabel);
        newPropertyjLabel.setBounds(20, 150, 40, 14);

        newNameProertField.setBorder(null);
        newPropertyjPanel.add(newNameProertField);
        newNameProertField.setBounds(89, 71, 180, 22);

        newPricePropertyField.setBorder(null);
        newPropertyjPanel.add(newPricePropertyField);
        newPricePropertyField.setBounds(89, 108, 180, 22);

        newTypePropertyjComboBox.setBackground(new java.awt.Color(204, 204, 204));
        newTypePropertyjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aparatment", "Duplex", "Houes", "Studio", "Room", "Villa" }));
        newPropertyjPanel.add(newTypePropertyjComboBox);
        newTypePropertyjComboBox.setBounds(89, 149, 180, 20);

        newFrunjLabel.setText("Furniture");
        newPropertyjPanel.add(newFrunjLabel);
        newFrunjLabel.setBounds(20, 190, 60, 14);

        newFurnjComboBox.setBackground(new java.awt.Color(204, 204, 204));
        newFurnjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unfurnished", "Partially Furnished", "Fully Furnished" }));
        newPropertyjPanel.add(newFurnjComboBox);
        newFurnjComboBox.setBounds(89, 189, 180, 20);

        newFacjLabel.setText("Facitltise");
        newPropertyjPanel.add(newFacjLabel);
        newFacjLabel.setBounds(296, 74, 60, 14);

        newMutltiCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        newMutltiCheckBox.setText("Multi-purpose Hall");
        newPropertyjPanel.add(newMutltiCheckBox);
        newMutltiCheckBox.setBounds(360, 70, 130, 23);

        newGymCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        newGymCheckBox.setText("Gym");
        newPropertyjPanel.add(newGymCheckBox);
        newGymCheckBox.setBounds(360, 150, 130, 23);

        newSkyCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        newSkyCheckBox.setText("Sky Lounge");
        newPropertyjPanel.add(newSkyCheckBox);
        newSkyCheckBox.setBounds(510, 70, 120, 23);

        newCarCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        newCarCheckBox.setText("Car Park");
        newPropertyjPanel.add(newCarCheckBox);
        newCarCheckBox.setBounds(650, 110, 112, 23);

        newPlayCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        newPlayCheckBox.setText("Play Ground");
        newPropertyjPanel.add(newPlayCheckBox);
        newPlayCheckBox.setBounds(650, 70, 112, 23);

        newSwimmCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        newSwimmCheckBox.setText("Swimming Pool");
        newPropertyjPanel.add(newSwimmCheckBox);
        newSwimmCheckBox.setBounds(510, 110, 120, 23);

        newReadingCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        newReadingCheckBox.setText("Reading Room");
        newPropertyjPanel.add(newReadingCheckBox);
        newReadingCheckBox.setBounds(360, 110, 130, 23);

        newImagePropertyjLabel.setText("Image");
        newPropertyjPanel.add(newImagePropertyjLabel);
        newImagePropertyjLabel.setBounds(290, 230, 50, 14);

        addNewProertyImage.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        addNewProertyImage.setForeground(new java.awt.Color(255, 255, 255));
        addNewProertyImage.setText("No Image Yet");
        newPropertyjPanel.add(addNewProertyImage);
        addNewProertyImage.setBounds(407, 247, 250, 200);

        clearPropertyFiledBtn.setBackground(new java.awt.Color(204, 204, 204));
        clearPropertyFiledBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_erase_26px_1.png"))); // NOI18N
        clearPropertyFiledBtn.setText("Clear");
        clearPropertyFiledBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPropertyFiledBtnActionPerformed(evt);
            }
        });
        newPropertyjPanel.add(clearPropertyFiledBtn);
        clearPropertyFiledBtn.setBounds(60, 340, 120, 35);

        newPrpertyselectBtn.setBackground(new java.awt.Color(204, 204, 204));
        newPrpertyselectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_picture_26px.png"))); // NOI18N
        newPrpertyselectBtn.setText("Select File");
        newPrpertyselectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPrpertyselectBtnActionPerformed(evt);
            }
        });
        newPropertyjPanel.add(newPrpertyselectBtn);
        newPrpertyselectBtn.setBounds(210, 340, 130, 35);

        newPropertSubmitBtn.setBackground(new java.awt.Color(204, 204, 204));
        newPropertSubmitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_add_property_26px.png"))); // NOI18N
        newPropertSubmitBtn.setText("Submit");
        newPropertSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPropertSubmitBtnActionPerformed(evt);
            }
        });
        newPropertyjPanel.add(newPropertSubmitBtn);
        newPropertSubmitBtn.setBounds(150, 410, 120, 35);

        newActivationLabel.setText("Activation");
        newPropertyjPanel.add(newActivationLabel);
        newActivationLabel.setBounds(20, 230, 60, 14);

        newActivationjComboBox.setBackground(new java.awt.Color(204, 204, 204));
        newActivationjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        newPropertyjPanel.add(newActivationjComboBox);
        newActivationjComboBox.setBounds(90, 230, 180, 20);

        newBookjLabel.setText("Book");
        newPropertyjPanel.add(newBookjLabel);
        newBookjLabel.setBounds(20, 270, 60, 14);

        newBookjComboBox.setBackground(new java.awt.Color(204, 204, 204));
        newBookjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Booked" }));
        newPropertyjPanel.add(newBookjComboBox);
        newBookjComboBox.setBounds(90, 270, 180, 20);

        containrjPanel.addTab("tab4", newPropertyjPanel);

        editPropertyjPanel.setBackground(new java.awt.Color(115, 181, 239));

        editNamejLabel.setText("Name");

        editPricejLabel.setText("Price");

        editTypejLabel.setText("Type");

        editNameField.setBorder(null);

        editPriceField.setBorder(null);

        editTypejComboBox.setBackground(new java.awt.Color(204, 204, 204));
        editTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aparatment", "Duplex", "Houes", "Studio", "Room", "Villa" }));

        editFurniturejLabel.setText("Furniture");

        editFurniturejComboBox.setBackground(new java.awt.Color(204, 204, 204));
        editFurniturejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unfurnished", "Partially Furnished", "Fully Furnished" }));

        editFacitltisejLabel.setText("Facitltise");

        editMultijCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        editMultijCheckBox.setText("Multi-purpose Hall");

        editPlayjCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        editPlayjCheckBox.setText("Play Ground");

        editSkyjCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        editSkyjCheckBox.setText("Sky Lounge");

        editGymjCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        editGymjCheckBox.setText("Gym");

        editCarParkjCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        editCarParkjCheckBox.setText("Car Park");

        editPooljCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        editPooljCheckBox.setText("Swimming Pool");

        editReadingjCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        editReadingjCheckBox.setText("Reading Room");

        editBookjLabel.setText("Book");

        editImagejLabel.setText("Image");

        newImage.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        newImage.setForeground(new java.awt.Color(255, 255, 255));
        newImage.setText("No Image Yet");

        editActivationjLabel.setText("Activation");

        editDeletetBtn.setBackground(new java.awt.Color(204, 204, 204));
        editDeletetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_delete_file_26px_3.png"))); // NOI18N
        editDeletetBtn.setText("Delete");
        editDeletetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDeletetBtnActionPerformed(evt);
            }
        });

        newPicturejLabel.setText("New Picture");

        oldPicturejLabel.setText("Old Picture");

        editTableViewProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name ", "Price", "Type", "Furniture", "Facitltise", "Activeation", "Book", "Comment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        editTableViewProperties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editTableViewPropertiesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(editTableViewProperties);

        editSubmitBtn.setBackground(new java.awt.Color(204, 204, 204));
        editSubmitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_submit_document_24px.png"))); // NOI18N
        editSubmitBtn.setText("Submit");
        editSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSubmitBtnActionPerformed(evt);
            }
        });

        editActivationjComboBox.setBackground(new java.awt.Color(204, 204, 204));
        editActivationjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        editBookjComboBox.setBackground(new java.awt.Color(204, 204, 204));
        editBookjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Booked" }));

        editselectPictureBtn.setBackground(new java.awt.Color(204, 204, 204));
        editselectPictureBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_picture_26px.png"))); // NOI18N
        editselectPictureBtn.setText("Select Image");
        editselectPictureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editselectPictureBtnActionPerformed(evt);
            }
        });

        loadDataBtn.setBackground(new java.awt.Color(204, 204, 204));
        loadDataBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_data_backup_26px.png"))); // NOI18N
        loadDataBtn.setText("Load Data");
        loadDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDataBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPropertyjPanelLayout = new javax.swing.GroupLayout(editPropertyjPanel);
        editPropertyjPanel.setLayout(editPropertyjPanelLayout);
        editPropertyjPanelLayout.setHorizontalGroup(
            editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(editDeletetBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editSubmitBtn))
                            .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                                .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(editPricejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editNamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editTypejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editActivationjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editFurniturejLabel))
                                    .addComponent(editBookjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(editPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(editTypejComboBox, 0, 180, Short.MAX_VALUE)
                                    .addComponent(editFurniturejComboBox, 0, 180, Short.MAX_VALUE)
                                    .addComponent(editActivationjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editBookjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(loadDataBtn)))
                .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                                .addComponent(newImage, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imageOld, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                                .addComponent(editImagejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newPicturejLabel)
                                .addGap(56, 56, 56)
                                .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editSkyjCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editPooljCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editPlayjCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editCarParkjCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(editGymjCheckBox)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPropertyjPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editFacitltisejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editselectPictureBtn)
                                    .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(editReadingjCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editMultijCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(334, 334, 334))))
                    .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oldPicturejLabel)
                        .addGap(153, 153, 153))))
        );
        editPropertyjPanelLayout.setVerticalGroup(
            editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editNamejLabel)
                            .addComponent(editNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editFacitltisejLabel)
                            .addComponent(editMultijCheckBox)
                            .addComponent(editSkyjCheckBox)
                            .addComponent(editPlayjCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editPricejLabel)
                            .addComponent(editPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editReadingjCheckBox)
                            .addComponent(editPooljCheckBox)
                            .addComponent(editCarParkjCheckBox)))
                    .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(editGymjCheckBox)))
                .addGap(18, 18, 18)
                .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                        .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                                .addComponent(editTypejLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPropertyjPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                                .addComponent(editFurniturejLabel)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPropertyjPanelLayout.createSequentialGroup()
                                .addComponent(editFurniturejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                        .addComponent(editselectPictureBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(newPicturejLabel)
                                .addComponent(editImagejLabel))
                            .addComponent(oldPicturejLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editActivationjLabel)
                            .addComponent(editActivationjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editBookjLabel)
                            .addComponent(editBookjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(loadDataBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editSubmitBtn)
                            .addComponent(editDeletetBtn)))
                    .addGroup(editPropertyjPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(editPropertyjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imageOld, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newImage, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86))
        );

        containrjPanel.addTab("tab6", editPropertyjPanel);

        getContentPane().add(containrjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -50, 820, 600));

        menuBar.setBackground(new java.awt.Color(204, 204, 204));

        fileMenu.setBackground(new java.awt.Color(204, 204, 204));
        fileMenu.setBorder(null);
        fileMenu.setText("File");

        addNewPropertMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_new_copy_26px.png"))); // NOI18N
        addNewPropertMenu.setText("New Property");
        addNewPropertMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewPropertMenuActionPerformed(evt);
            }
        });
        fileMenu.add(addNewPropertMenu);
        fileMenu.add(jSeparatorMenu);

        exitjMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_cancel_26px.png"))); // NOI18N
        exitjMenu.setText("Exit");
        exitjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitjMenuActionPerformed(evt);
            }
        });
        fileMenu.add(exitjMenu);

        menuBar.add(fileMenu);

        editjMenu.setBackground(new java.awt.Color(204, 204, 204));
        editjMenu.setText("Edit");

        editPropertyjMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_edit_property_26px.png"))); // NOI18N
        editPropertyjMenuItem.setText("Edit Property");
        editPropertyjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPropertyjMenuItemActionPerformed(evt);
            }
        });
        editjMenu.add(editPropertyjMenuItem);

        menuBar.add(editjMenu);

        viewjMenu.setBackground(new java.awt.Color(204, 204, 204));
        viewjMenu.setText("View");

        viewPropertyjMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_show_property_26px.png"))); // NOI18N
        viewPropertyjMenuItem.setText("View Property");
        viewPropertyjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPropertyjMenuItemActionPerformed(evt);
            }
        });
        viewjMenu.add(viewPropertyjMenuItem);

        menuBar.add(viewjMenu);

        helpjMenu.setBackground(new java.awt.Color(204, 204, 204));
        helpjMenu.setText("Help");

        helpjMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_help_26px.png"))); // NOI18N
        helpjMenuItem.setText("Help !");
        helpjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpjMenuItemActionPerformed(evt);
            }
        });
        helpjMenu.add(helpjMenuItem);

        aboutUsjMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rental/system/Icons/icons8_about_26px.png"))); // NOI18N
        aboutUsjMenuItem.setText("About Us !");
        aboutUsjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsjMenuItemActionPerformed(evt);
            }
        });
        helpjMenu.add(aboutUsjMenuItem);

        menuBar.add(helpjMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewPropertMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewPropertMenuActionPerformed
        // TODO add your handling code here:
        containrjPanel.setSelectedIndex(0);
    }//GEN-LAST:event_addNewPropertMenuActionPerformed

    private void exitjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitjMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitjMenuActionPerformed

    private void editPropertyjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPropertyjMenuItemActionPerformed
        // TODO add your handling code here:
        containrjPanel.setSelectedIndex(1);
    }//GEN-LAST:event_editPropertyjMenuItemActionPerformed

    private void viewPropertyjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPropertyjMenuItemActionPerformed
        // TODO add your handling code here:
        containrjPanel.setSelectedIndex(1);
    }//GEN-LAST:event_viewPropertyjMenuItemActionPerformed

    private void helpjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpjMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "A tenant must register to the system in order to view or rent properties.\n"
                + "After the tenant creates an account, an approval from the management will be needed for to use the application.\n"
                + "An agent or an owner can use the application to publish their properties and they can make any modifications needed.\n"
                + "A management approval is also required for agents or owners to use their accounts.", "Help", 1);
    }//GEN-LAST:event_helpjMenuItemActionPerformed

    private void aboutUsjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsjMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Our application provides an easy to use online platform for accommodation rental. \n"
                + "We aim to make our application to be user friendly for those who are willing to \n"
                + "rent accommodation and also for oweners and agents who are looking for tenants for their properties.", "About Us", 1);

    }//GEN-LAST:event_aboutUsjMenuItemActionPerformed

    private void newPropertyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPropertyBtnActionPerformed
        // TODO add your handling code here:
        containrjPanel.setSelectedIndex(0);
    }//GEN-LAST:event_newPropertyBtnActionPerformed

    private void editPropertyrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPropertyrBtnActionPerformed
        // TODO add your handling code here:
        containrjPanel.setSelectedIndex(1);
    }//GEN-LAST:event_editPropertyrBtnActionPerformed

    private void clearPropertyFiledBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPropertyFiledBtnActionPerformed
        // TODO add your handling code here:
        clearFieldAddingProperty();
    }//GEN-LAST:event_clearPropertyFiledBtnActionPerformed

    private void newPrpertyselectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPrpertyselectBtnActionPerformed
        // TODO add your handling code here:
        pickupSelectedImage();
    }//GEN-LAST:event_newPrpertyselectBtnActionPerformed

    private void newPropertSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPropertSubmitBtnActionPerformed
        // TODO add your handling code here:
        submitNewProperty();
    }//GEN-LAST:event_newPropertSubmitBtnActionPerformed

    private void editTableViewPropertiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editTableViewPropertiesMouseClicked
        // TODO add your handling code here:
        filtering(getSelectedProperty(editTableViewProperties));
    }//GEN-LAST:event_editTableViewPropertiesMouseClicked

    private void loadDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDataBtnActionPerformed
        // TODO add your handling code here:
        displayPropertiesInfo();
    }//GEN-LAST:event_loadDataBtnActionPerformed

    private void editDeletetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDeletetBtnActionPerformed
        // TODO add your handling code here:
        control.deleteProperty(property);
    }//GEN-LAST:event_editDeletetBtnActionPerformed

    private void editselectPictureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editselectPictureBtnActionPerformed
        // TODO add your handling code here:
        pickupSelecteEditdImage();

    }//GEN-LAST:event_editselectPictureBtnActionPerformed

    private void editSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSubmitBtnActionPerformed
        // TODO add your handling code here:
        submitEditProperty();
    }//GEN-LAST:event_editSubmitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentOwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentOwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentOwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentOwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentOwnerPage(user).setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Icons/icon.jpg")));
    }

    private String getFacitltiseSelected() {
        String hold = "";
        if (newCarCheckBox.isSelected()) {
            hold += "Car Park, ";
        }
        if (newMutltiCheckBox.isSelected()) {
            hold += "Multi-purpose Hall, ";
        }
        if (newSkyCheckBox.isSelected()) {
            hold += "Sky Lounge, ";
        }
        if (newPlayCheckBox.isSelected()) {
            hold += "Play Ground, ";
        }
        if (newReadingCheckBox.isSelected()) {
            hold += "Reading Room, ";
        }
        if (newSwimmCheckBox.isSelected()) {
            hold += "Swimming Pool, ";
        }
        if (newGymCheckBox.isSelected()) {
            hold += "Gym, ";
        }
        return hold;
    }

    private void clearFieldAddingProperty() {
        newImagePath = "";
        addNewProertyImage.setText("No Image Yet");
        addNewProertyImage.setIcon(null);
        newNameProertField.setText(null);
        newPricePropertyField.setText(null);
        newTypePropertyjComboBox.setSelectedIndex(0);
        newFurnjComboBox.setSelectedIndex(0);
        newActivationjComboBox.setSelectedIndex(0);
        newBookjComboBox.setSelectedIndex(0);
        newMutltiCheckBox.setSelected(false);
        newCarCheckBox.setSelected(false);
        newSkyCheckBox.setSelected(false);
        newPlayCheckBox.setSelected(false);
        newReadingCheckBox.setSelected(false);
        newSwimmCheckBox.setSelected(false);
        newGymCheckBox.setSelected(false);
    }

    private void pickupSelectedImage() {
        this.addNewProertyImage.setText(null);
        JFileChooser jFileChooser1 = new JFileChooser();
        jFileChooser1.showOpenDialog(null);
        File f = jFileChooser1.getSelectedFile();
        newImagePath = f.getAbsolutePath();
        ImageIcon image = new ImageIcon(newImagePath);
        Image img = image.getImage();
        Image imgFit = img.getScaledInstance(this.addNewProertyImage.getWidth(), this.addNewProertyImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon fit = new ImageIcon(imgFit);
        this.addNewProertyImage.setIcon(fit);
    }

    private void submitNewProperty() {
        String correctPath = newImagePath;
        correctPath = correctPath.replace("\\", "\\\\");
        try {
            Double.parseDouble(newPricePropertyField.getText());
            Property p = new Property(newNameProertField.getText(), Double.parseDouble(newPricePropertyField.getText()), newTypePropertyjComboBox.getSelectedItem().toString(), newFurnjComboBox.getSelectedItem().toString(), getFacitltiseSelected(), correctPath, newActivationjComboBox.getSelectedItem().toString(), newBookjComboBox.getSelectedItem().toString(), this.user.getId());
            control.insertPropertyToDB(p);
            clearFieldAddingProperty();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "The Price Must be in Decmail Fromaat", "Error", 0);
        }
    }

    private void displayPropertiesInfo() {
        holdTheDataOfProperties = control.importPropertyDataFromDB(user);
        DefaultTableModel model = (DefaultTableModel) editTableViewProperties.getModel();
        model.getDataVector().removeAllElements();
        revalidate();
        Object[] row = new Object[10];

        for (int i = 0; i < holdTheDataOfProperties.size(); i++) {
            row[0] = holdTheDataOfProperties.get(i).getId();
            row[1] = holdTheDataOfProperties.get(i).getName();
            row[2] = holdTheDataOfProperties.get(i).getPrice();
            row[3] = holdTheDataOfProperties.get(i).getType();
            row[4] = holdTheDataOfProperties.get(i).getFurniture();
            row[5] = holdTheDataOfProperties.get(i).getFacility();
            row[6] = holdTheDataOfProperties.get(i).getActivation();
            row[7] = holdTheDataOfProperties.get(i).getBook();
            row[8] = holdTheDataOfProperties.get(i).getComment();
            row[9] = holdTheDataOfProperties.get(i).getUserId();
            model.addRow(row);

        }
    }

    private Property getSelectedProperty(JTable t) {
        int index = t.getSelectedRow();
        TableModel model = t.getModel();
        if (index >= 0) {
            int id = Integer.parseInt(model.getValueAt(index, 0).toString());

            for (int i = 0; i < holdTheDataOfProperties.size(); i++) {
                if (holdTheDataOfProperties.get(i).getId() == id) {
                    putOldImage(holdTheDataOfProperties.get(i).getPhoto());
                    return property = holdTheDataOfProperties.get(i);
                }
            }
        }
        return new Property();
    }

    private void putOldImage(String path) {

        ImageIcon image = new ImageIcon(path);
        Image img = image.getImage();
        Image imgFit = img.getScaledInstance(imageOld.getWidth(), imageOld.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon fit = new ImageIcon(imgFit);
        imageOld.setIcon(fit);
    }

    private void clearFieldEditingProperty() {
        editImagePath = "";
        newImage.setText("No Image Yet");
        newImage.setIcon(null);
        imageOld.setIcon(null);
        editNameField.setText(null);
        editPriceField.setText(null);
        editTypejComboBox.setSelectedIndex(0);
        editFurniturejComboBox.setSelectedIndex(0);
        editActivationjComboBox.setSelectedIndex(0);
        editBookjComboBox.setSelectedIndex(0);
        editMultijCheckBox.setSelected(false);
        editSkyjCheckBox.setSelected(false);
        editPlayjCheckBox.setSelected(false);
        editReadingjCheckBox.setSelected(false);
        editPooljCheckBox.setSelected(false);
        editCarParkjCheckBox.setSelected(false);
        editGymjCheckBox.setSelected(false);
    }

    private void pickupSelecteEditdImage() {
        this.newImage.setText(null);
        JFileChooser jFileChooser1 = new JFileChooser();
        jFileChooser1.showOpenDialog(null);
        File f = jFileChooser1.getSelectedFile();
        editImagePath = f.getAbsolutePath();
        ImageIcon image = new ImageIcon(editImagePath);
        Image img = image.getImage();
        Image imgFit = img.getScaledInstance(this.newImage.getWidth(), this.newImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon fit = new ImageIcon(imgFit);
        this.newImage.setIcon(fit);
    }

    private void submitEditProperty() {
        String correctPath = editImagePath;
        correctPath = correctPath.replace("\\", "\\\\");
        try {
            Double.parseDouble(editPriceField.getText());
            Property p = new Property(property.getId(), editNameField.getText(), Double.parseDouble(editPriceField.getText()), editTypejComboBox.getSelectedItem().toString(), editFurniturejComboBox.getSelectedItem().toString(), getEditFacitltiseSelected(), correctPath, editActivationjComboBox.getSelectedItem().toString(), editBookjComboBox.getSelectedItem().toString(), this.user.getId());
            control.updatePropertyInof(p);
            clearFieldEditingProperty();
            displayPropertiesInfo();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "The Price Must be in Decimal Format", "Error", 0);
        }
    }

    private String getEditFacitltiseSelected() {
        String hold = "";
        if (editCarParkjCheckBox.isSelected()) {
            hold += "Car Park, ";
        }
        if (editMultijCheckBox.isSelected()) {
            hold += "Multi-purpose Hall, ";
        }
        if (editSkyjCheckBox.isSelected()) {
            hold += "Sky Lounge, ";
        }
        if (editPlayjCheckBox.isSelected()) {
            hold += "Play Ground, ";
        }
        if (editReadingjCheckBox.isSelected()) {
            hold += "Reading Room, ";
        }
        if (editPooljCheckBox.isSelected()) {
            hold += "Swimming Pool, ";
        }
        if (editGymjCheckBox.isSelected()) {
            hold += "Gym, ";
        }
        return hold;
    }

    private void filtering(Property p) {

        editNameField.setText(p.getName());
        editPriceField.setText(String.valueOf(p.getPrice()));
        editTypejComboBox.setSelectedItem(p.getType());
        editActivationjComboBox.setSelectedItem(p.getActivation());
        editFurniturejComboBox.setSelectedItem(p.getFurniture());
        editBookjComboBox.setSelectedItem(p.getBook());

        getFac(p.getFacility());

    }

    private void getFac(String s) {
        editMultijCheckBox.setSelected(false);
        editSkyjCheckBox.setSelected(false);
        editPlayjCheckBox.setSelected(false);
        editReadingjCheckBox.setSelected(false);
        editPooljCheckBox.setSelected(false);
        editCarParkjCheckBox.setSelected(false);
        editGymjCheckBox.setSelected(false);

        String[] parts = s.split(", ");
        for (int i = 0; i < parts.length; i++) {
            if (parts[i].equals("Multi-purpose Hall")) {
                editMultijCheckBox.setSelected(true);
            }
            if (parts[i].equals("Sky Lounge")) {
                editSkyjCheckBox.setSelected(true);
            }
            if (parts[i].equals("Play Ground")) {
                editPlayjCheckBox.setSelected(true);
            }
            if (parts[i].equals("Reading Room")) {
                editReadingjCheckBox.setSelected(true);
            }
            if (parts[i].equals("Swimming Pool")) {
                editPooljCheckBox.setSelected(true);
            }
            if (parts[i].equals("Car Park")) {
                editCarParkjCheckBox.setSelected(true);
            }
            if (parts[i].equals("Gym")) {
                editGymjCheckBox.setSelected(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutUsjMenuItem;
    private javax.swing.JLabel addNewProertyImage;
    private javax.swing.JMenuItem addNewPropertMenu;
    private javax.swing.JPanel barjPanel;
    private javax.swing.JButton clearPropertyFiledBtn;
    private javax.swing.JTabbedPane containrjPanel;
    private javax.swing.JComboBox<String> editActivationjComboBox;
    private javax.swing.JLabel editActivationjLabel;
    private javax.swing.JComboBox<String> editBookjComboBox;
    private javax.swing.JLabel editBookjLabel;
    private javax.swing.JCheckBox editCarParkjCheckBox;
    private javax.swing.JButton editDeletetBtn;
    private javax.swing.JLabel editFacitltisejLabel;
    private javax.swing.JComboBox<String> editFurniturejComboBox;
    private javax.swing.JLabel editFurniturejLabel;
    private javax.swing.JCheckBox editGymjCheckBox;
    private javax.swing.JLabel editImagejLabel;
    private javax.swing.JCheckBox editMultijCheckBox;
    private javax.swing.JTextField editNameField;
    private javax.swing.JLabel editNamejLabel;
    private javax.swing.JCheckBox editPlayjCheckBox;
    private javax.swing.JCheckBox editPooljCheckBox;
    private javax.swing.JTextField editPriceField;
    private javax.swing.JLabel editPricejLabel;
    private javax.swing.JMenuItem editPropertyjMenuItem;
    private javax.swing.JPanel editPropertyjPanel;
    private javax.swing.JButton editPropertyrBtn;
    private javax.swing.JCheckBox editReadingjCheckBox;
    private javax.swing.JCheckBox editSkyjCheckBox;
    private javax.swing.JButton editSubmitBtn;
    private javax.swing.JTable editTableViewProperties;
    private javax.swing.JComboBox<String> editTypejComboBox;
    private javax.swing.JLabel editTypejLabel;
    private javax.swing.JMenu editjMenu;
    private javax.swing.JButton editselectPictureBtn;
    private javax.swing.JMenuItem exitjMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpjMenu;
    private javax.swing.JMenuItem helpjMenuItem;
    private javax.swing.JLabel imageOld;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparatorMenu;
    private javax.swing.JButton loadDataBtn;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel newActivationLabel;
    private javax.swing.JComboBox<String> newActivationjComboBox;
    private javax.swing.JComboBox<String> newBookjComboBox;
    private javax.swing.JLabel newBookjLabel;
    private javax.swing.JCheckBox newCarCheckBox;
    private javax.swing.JLabel newFacjLabel;
    private javax.swing.JLabel newFrunjLabel;
    private javax.swing.JComboBox<String> newFurnjComboBox;
    private javax.swing.JCheckBox newGymCheckBox;
    private javax.swing.JLabel newImage;
    private javax.swing.JLabel newImagePropertyjLabel;
    private javax.swing.JCheckBox newMutltiCheckBox;
    private javax.swing.JTextField newNameProertField;
    private javax.swing.JLabel newNamePropertjLabel;
    private javax.swing.JLabel newPicturejLabel;
    private javax.swing.JCheckBox newPlayCheckBox;
    private javax.swing.JTextField newPricePropertyField;
    private javax.swing.JLabel newPricejLabel;
    private javax.swing.JButton newPropertSubmitBtn;
    private javax.swing.JButton newPropertyBtn;
    private javax.swing.JLabel newPropertyjLabel;
    private javax.swing.JPanel newPropertyjPanel;
    private javax.swing.JButton newPrpertyselectBtn;
    private javax.swing.JCheckBox newReadingCheckBox;
    private javax.swing.JCheckBox newSkyCheckBox;
    private javax.swing.JCheckBox newSwimmCheckBox;
    private javax.swing.JComboBox<String> newTypePropertyjComboBox;
    private javax.swing.JLabel oldPicturejLabel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userIdjLabel;
    private javax.swing.JLabel userNamejLabel;
    private javax.swing.JLabel userTypejLabel;
    private javax.swing.JMenuItem viewPropertyjMenuItem;
    private javax.swing.JMenu viewjMenu;
    // End of variables declaration//GEN-END:variables
}
